### ISSUE TITLE
Unable to edit stored values

### ISSUE THREAD

**Issue by nurrrr** [ibm-cds-labs/concierge#2]
Hi guys,

I need your quick help. Running the concierge, I've entered a wrong password and now all details stored somewhere locally and I am having a trouble altering them, as the code is giving me default values. I deleted the concierge-chatbot by running npm uninstall concierge-chatbot and restarted the pc, but still facing an issue.
Any ideas where did it store and how I can delete it?

![image](https://user-images.githubusercontent.com/29379419/27042418-eb872942-4fa7-11e7-83d6-d1747b750599.png)

Thanks.
Nur

**Comment by vabarbosa** [comment]
@nurrrr have you looked for/at the file: `<user_home>/.concierge.json`

**Comment by nurrrr** [comment]
thanks, got it.
one more question, [offtopic], why the code is trying to post to the 
`url: 'https://gateway.watsonplatform.net/conversation/api/v1/workspaces/' + msg.workspace + '/message?version=2016-09-20',`  in actions.js ?

Should I change it to the `https://www.ibmwatsonconversation.com/us-south/894219d9-f8e6-496e-a1e9-bb8a3d953c65/workspaces`

**Comment by vabarbosa** [comment]
that is the conversarion service REST endpoint (`POST /v1/workspaces/{workspace_id}/message`) for sending messages according to the API doc [https://www.ibm.com/watson/developercloud/conversation/api/v1/#send_message](https://www.ibm.com/watson/developercloud/conversation/api/v1/#send_message)

**Comment by nurrrr** [comment]
thanks.
